package lb5;
public class TestErrorException extends Exception{
	public void TestErrorException() {
		System.out.println("Возникло исключение!");
	}
}
